# Generated by Django 3.2.12 on 2022-05-20 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GunType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun_name', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('gun_weight', models.CharField(max_length=50)),
                ('gun_length', models.CharField(max_length=50)),
                ('gun_caliber', models.CharField(max_length=50)),
                ('gun_image_path', models.CharField(max_length=200)),
                ('gun_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guns.guntype')),
                ('like_users', models.ManyToManyField(blank=True, related_name='like_guns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
