# Generated by Django 3.2.12 on 2022-05-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gun',
            name='gun_youtube_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
